### ISSUE TITLE
Add & Recover wasm src for as-ffi-bindings

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa-unit-tests-src#13]
At least 1 source is avail here:

https://github.com/massalabs/as-ffi-bindings/blob/06f628b01ca08ccb90dd057b566983fe00dcf785/tests/README.md

**Comment by sydhds** [comment]
Partially done in PR: #15

**Comment by AurelienFT** [comment]
@sydhds is this still relevant ?

**Comment by sydhds** [comment]
Should be ok now. Closing it...
